[[plugins]]

repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = 'c'
on_ft = 'cpp'

[[plugins]]
repo = 'cocopon/colorswatch.vim'
on_ft = 'vim'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'ujihisa/neco-ghc'
on_ft = 'haskell'

[[plugins]]
repo = 'dag/vim2hs'
on_ft = 'haskell'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-surround'
