[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Align'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'ujihisa/neco-ghc'
on_ft = 'haskell'

[[plugins]]
repo = 'dag/vim2hs'
on_ft = 'haskell'
