[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
"" go runのキーマッピング  
au FileType go nmap gr (go-run)  
""" go testのキーマッピング  
au FileType go nmap gt (go-test)  
"" highlight  
let g:go_hightlight_functions = 1  
let g:go_hightlight_methods = 1  
let g:go_hightlight_structs = 1  
let g:go_hightlight_interfaces = 1  
let g:go_hightlight_operators = 1  
let g:go_hightlight_build_constraints = 1  
"" GoFmt時にインポートするパッケージを整理(GoFmtはファイル書き込み時に自動的に実行される)  
let g:go_fmt_command = "goimports"  
'''

[[plugins]]
repo = 'nsf/gocode'
on_ft = ['go']
hook_add = '''
'''

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['go']
hook_add = '''
let g:syntastic_mode_map = { 'mode': 'passive',
    \ 'active_filetypes': ['go'] }
    let g:syntastic_go_checkers = ['go', 'golint']
'''
