[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.vim/userautoload/plugins/plugins-denite.vim
'''

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['roxma/nvim-yarp', 'roxma/vim-hug-neovim-rpc']
hook_add = '''
  let g:deoplete#enable_at_statup = 1
'''

# ファイルエクスプローラー
[[plugins]]
repo = 'scrooloose/nerdtree' hook_add = ''' nnoremap <Space>f :<C-u>NERDTreeToggle<CR> let NERDTreeIgnore = ['\.pyc$']
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.vim/userautoload/plugins/plugins-lightline.vim
'''

# vimからGit
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  map [fugitive] <Nop>
  map <Leader>g [fugitive]
  nnoremap <silent> [fugitive]s :Gstatus<CR>
  nnoremap <silent> [fugitive]w :Gwrite<CR>
  nnoremap <silent> [fugitive]c :Gcommit<CR>
  nnoremap <silent> [fugitive]d :Gdiff<CR>
  nnoremap <silent> [fugitive]b :Gblame<CR>
'''

# gitで管理しているファイル編集時に差分を表示, 重い(更新タイミングを少なくして軽量化中)
[[plugins]]
repo = 'airblade/vim-gitgutter'
# http://wonderwall.hatenablog.com/entry/2016/03/26/211710
hook_add = '''
  let g:gitgutter_realtime = 0
  let g:gitgutter_eager = 0
'''

# nerdtreeにGitの状態を表示, 重い
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive', 'nerdtree']

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  nnoremap <C-q> :FZFileList<CR>
  command! FZFileList call fzf#run({
    \ 'source': 'find . -type d -name .git -prune -o ! -name .DS_Store',
    \ 'sink': 'e'})
  command! Fmru FZFMru
  command! FZFMru call fzf#run({
    \  'source':  v:oldfiles,
    \  'sink':    'tabe',
    \  'options': '-m -x +s',
    \  'down':    '40%'})
'''
