[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.vim/userautoload/plugins/plugins-denite.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
  source ~/.vim/userautoload/plugins/plugins-defx.vim
  nnoremap <silent><Space>f :Defx -split=vertical -winwidth=30 -direction=topleft<CR>
'''

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'
hook_add = '''
  let g:python3_host_prog = expand('/usr/bin/python3')
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.vim/userautoload/plugins/plugins-lightline.vim
'''

# vimからGit
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  map [fugitive] <Nop>
  map <Leader>g [fugitive]
  nnoremap <silent> [fugitive]s :Gstatus<CR>
  nnoremap <silent> [fugitive]w :Gwrite<CR>
  nnoremap <silent> [fugitive]c :Gcommit<CR>
  nnoremap <silent> [fugitive]d :Gdiff<CR>
  nnoremap <silent> [fugitive]b :Gblame<CR>
'''

# gitで管理しているファイル編集時に差分を表示, 重い(更新タイミングを少なくして軽量化中)
#[[plugins]]
#repo = 'airblade/vim-gitgutter'
## http://wonderwall.hatenablog.com/entry/2016/03/26/211710
#hook_add = '''
#  let g:gitgutter_realtime = 0
#  let g:gitgutter_eager = 0
#'''

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  nnoremap <C-q> :FZFileList<CR>
  command! FZFileList call fzf#run({
    \ 'source': 'find . -type d -name .git -prune -o ! -name .DS_Store',
    \ 'sink': 'e'})
  command! Fmru FZFMru
  command! FZFMru call fzf#run({
    \  'source':  v:oldfiles,
    \  'sink':    'tabe',
    \  'options': '-m -x +s',
    \  'down':    '40%'})
'''

[[plugins]]
repo = 'glidenote/memolist.vim'
# detail: http://blog.glidenote.com/blog/2012/03/26/memolist.vim/
hook_add = '''
  let g:memolist_path = "$HOME/memo"
  let g:memolist_gfixgrep             = 1
  let g:memolist_filename_prefix_none = 1
  nnoremap mn  :MemoNew<CR>
  nnoremap mg  :MemoGrep<CR>
'''

# deoplete
[[plugins]]
repo = 'Shougo/neoyank.vim'
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
depends = ['roxma/nvim-yarp', 'roxma/vim-hug-neovim-rpc']
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  " Tab補完
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
    \ neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''

[[plugins]]
repo = 'yuratomo/w3m.vim'
hook_add = '''
  let g:w3m#command = '/usr/bin/w3m'
  let g:w3m#external_browser = 'google-chrome-stable'
  let g:w3m#homepage = "http://www.google.co.jp/"
  let g:w3m#hit_a_hint_key = 'f'
  let g:w3m#lang = 'en_US'
'''

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  source ~/.vim/userautoload/plugins/plugins-ale.vim
'''
[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'neoclide/coc.nvim'
hook_add = '''
  source ~/.vim/userautoload/plugins/plugins-coc.vim
  nnoremap <silent>,h :sp<CR>:Defx<CR>
  nnoremap <silent>,v :vsplit<CR>:Defx<CR>
  nnoremap <silent>,e :Defx -split=vertical -winwidth=30 -direction=topleft<CR>
'''

[[plugins]]
repo = 'mattn/vim-sonictemplate'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
