# :checkhealth, :message
[[plugins]]
repo = 'Shougo/dein.vim'

# ddc
[[plugins]]
repo = 'vim-denops/denops.vim'
[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'
[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['vim-denops/denops.vim']
# Install your UIs
# popup
[[plugins]]
repo = 'Shougo/pum.vim'
depends = ['Shougo/ddu.vim']
# Install your sources
# カーソル周辺の既出単語補完 source
[[plugins]]
repo = 'Shougo/ddc-around'
depends = ['Shougo/ddc.vim']
# ファイル名補完補完 source
[[plugins]]
repo = 'LumaKernel/ddc-file'
depends = ['Shougo/ddc.vim']
# Install your filters
# 入力中の単語を補完の対象にする filter
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
depends = ['Shougo/ddc.vim']
# 補完候補を適切にソートする filter
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
depends = ['Shougo/ddc.vim']
# 補完候補の重複を防ぐための filter
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
depends = ['Shougo/ddc.vim']
# Install your kinds
# end ddc

# ddu
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['vim-denops/denops.vim']
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
[[plugins]]
repo = 'Shougo/ddu-source-file'
[[plugins]]
repo = 'Shougo/ddu-source-register'
[[plugins]]
repo = 'kuuote/ddu-source-mr'
[[plugins]]
repo = 'lambdalisue/mr.vim'
[[plugins]]
repo = 'shun/ddu-source-buffer'
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
[[plugins]]
repo = 'Shougo/ddu-commands.vim'
# ddu end

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'
hook_add = '''
  let g:python3_host_prog = expand('/usr/bin/python3')
'''

# Update: UpdateRemotePlugins<CR>, default dir: $XDG_CONFIG_HOME/nvim/
[[plugins]]
repo = 'Shougo/deoppet.nvim'
hook_add = '''
  source ~/.vim/userautoload/plugins/plugins-deoppet.vim
'''

# neo tree: Neotree
# :Neotree source=filesystem reveal=true position=left
# :Neotree /home
[[plugins]]
repo = 'nvim-neo-tree/neo-tree.nvim'
hook_add = '''
  source ~/.vim/userautoload/plugins/plugins-nvim-neo-tree.vim
'''
depends = ['nvim-lua/plenary.nvim', 'MunifTanjim/nui.nvim']
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
[[plugins]]
repo = 'MunifTanjim/nui.nvim'
# neo tree end

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.vim/userautoload/plugins/plugins-lightline.vim
'''

# :Copilot setup, :help copilot
[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['nvim-lua/plenary.nvim']
hook_add = '''
  source ~/.vim/userautoload/plugins/plugins-telescope.vim
'''

# :TSInstallinfo/TSUpdate <lang>/:TSUpdate all
# parser generator/incremental parsing library
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

# vimからGit
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  map [fugitive] <Nop>
  map <Leader>g [fugitive]
  nnoremap <silent> [fugitive]s :Git<CR>
  nnoremap <silent> [fugitive]w :Gwrite<CR>
  nnoremap <silent> [fugitive]c :Gcommit<CR>
  nnoremap <silent> [fugitive]d :Gdiff<CR>
  nnoremap <silent> [fugitive]b :Gblame<CR>
'''

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'neoclide/coc.nvim'
hook_add = '''
  source ~/.vim/userautoload/plugins/plugins-coc.vim
  nnoremap <silent>,h :sp<CR>:Defx<CR>
  nnoremap <silent>,v :vsplit<CR>:Defx<CR>
  nnoremap <silent>,e :Defx -split=vertical -winwidth=30 -direction=topleft<CR>
'''

# :help sonictemplate-vim-writetemplate
[[plugins]]
repo = 'mattn/vim-sonictemplate'
hook_add = '''
  let g:sonictemplate_vim_template_dir = '~/dotfiles/vim/template'
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'

# ale
#[[plugins]]
#repo = 'dense-analysis/ale'
#hook_add = '''
#  source ~/.vim/userautoload/plugins/plugins-ale.vim
#'''
#[[plugins]]
#repo = 'maximbaz/lightline-ale'
#depends = ['lightline.vim', 'ale']
