[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'javascript']

[[plugins]]
repo = 'mattn/webapi-vim'
on_ft = ['html', 'css', 'javascript']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'css', 'javascript']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['html', 'css', 'javascript']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['html', 'css', 'javascript']
